name: Check do Site da Daia

on: [push, pull_request]

jobs:
  verificacao:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar o c√≥digo
        uses: actions/checkout@v4

      - name: Validar HTML
        uses: htmlhint/htmlhint-action@v1
        with:
          pattern: '**/*.html'
